// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: create-users-table.sql

package database

import (
	"context"
)

const createUsersTable = `-- name: CreateUsersTable :exec
CREATE TABLE "users" (
  "id" serial NOT NULL UNIQUE PRIMARY KEY,
  "email" text NOT NULL UNIQUE
)
`

func (q *Queries) CreateUsersTable(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createUsersTable)
	return err
}
